### ISSUE TITLE
Mac M1 Driver Installation Window frozen

### ISSUE THREAD

**Issue by alfechner** [WCHSoftGroup/ch34xser_macos#8]
I try to follow the docs on installing the driver on my M1 MacBook Pro. When clicking the `install` button exactly nothing happens. The Window doesn't change or close:

![image](https://user-images.githubusercontent.com/7656306/186518490-6165aaa0-36fd-436d-a49e-470815527af1.png)

Do I miss anything?

Thanks for all your work!

**Comment by moyun-yinyun** [comment]
> I try to follow the docs on installing the driver on my M1 MacBook Pro. When clicking the `install` button exactly nothing happens. The Window doesn't change or close:
> 
> ![image](https://user-images.githubusercontent.com/7656306/186518490-6165aaa0-36fd-436d-a49e-470815527af1.png)
> 
> Do I miss anything?
> 
> Thanks for all your work!

please use this command "systemextensionsctl list" in terminal. if cn.wch.CH34xVCPDriver state is [activated enabled] the driver install success.

systemextensionsctl list
1 extension(s)
--- com.apple.system_extension.driver_extension
enabled	active	teamID	bundleID (version)	name	[state]
*	*	5JZGQTGU4W	cn.wch.CH34xVCPDriver (1.0/1)	cn.wch.CH34xVCPDriver	[activated enabled]

**Comment by alfechner** [comment]
@moyun-yinyun thanks a lot for your reply.

My state is `activated waiting for user` I guess. Do you know what that means?

![image](https://user-images.githubusercontent.com/7656306/186594982-7aa4d75a-de25-4329-8447-579b91affb0e.png)

**Comment by moyun-yinyun** [comment]
> @moyun-yinyun thanks a lot for your reply.
> 
> My state is `activated waiting for user` I guess. Do you know what that means?
> 
> ![image](https://user-images.githubusercontent.com/7656306/186594982-7aa4d75a-de25-4329-8447-579b91affb0e.png)

You need authorization to drive extensions in the security and privacy Settings in the system preferences

**Comment by alfechner** [comment]
Thanks, that solved the issue. Seeing `activated enabled` now 👍
